/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "\n\tquery CourseFeedPost($articleId: String!, $commentsId: String!) {\n\t\tactivityFeedCommentPage(id: $commentsId) {\n\t\t\tactivityFeedComments {\n\t\t\t\tid\n\t\t\t\ttype\n\t\t\t\tauthor {\n\t\t\t\t\timageUrl\n\t\t\t\t\tdisplayName\n\t\t\t\t}\n\t\t\t\tmessage\n\t\t\t}\n        }\n\t\tactivityFeedArticle(id: $articleId) {\n            ... on ActivityFeedEntity {\n                ...FeedItemFragment\n            }\n            ... on ActivityFeedTopLevelPost {\n                ...FeedPostFragment\n            }\n            ... on ActivityFeedArticle {\n                ...ArticleDetailsFragment\n            }\n            ... on ActivityFeedAssignment {\n                ...AssignmentDetailsFragment\n            }\n        }\n    }\n": types.CourseFeedPostDocument,
    "\n    query CoursePage($id: String!, $orgUnitId: String!) {\n        organization(id: $id) {\n            name\n            imageUrl\n            homeUrl\n        }\n        activityFeedArticlePage(orgUnitId: $orgUnitId) {\n            id\n            activityFeedArticles {\n                __typename\n                ... on ActivityFeedEntity {\n                    ...FeedItemFragment\n                }\n                ... on ActivityFeedTopLevelPost {\n                    ...FeedPostFragment\n                }\n                ... on ActivityFeedArticle {\n                    ...ArticleDetailsFragment\n                }\n                ... on ActivityFeedAssignment {\n                    ...AssignmentDetailsFragment\n                }\n            }\n        }\n    }\n    fragment FeedItemFragment on ActivityFeedEntity {\n        id\n        type\n        author {\n            displayName\n            imageUrl\n        }\n        publishedDate\n    }\n    fragment FeedPostFragment on ActivityFeedTopLevelPost {\n        commentsLink\n        commentsCount\n        attachmentLinks {\n            id\n            type\n            name\n            href\n            iconHref\n        }\n        isPinned\n    }\n    fragment ArticleDetailsFragment on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetailsFragment on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n": types.CoursePageDocument,
    "\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.CourseListDocument,
};

export function graphql(source: "\n\tquery CourseFeedPost($articleId: String!, $commentsId: String!) {\n\t\tactivityFeedCommentPage(id: $commentsId) {\n\t\t\tactivityFeedComments {\n\t\t\t\tid\n\t\t\t\ttype\n\t\t\t\tauthor {\n\t\t\t\t\timageUrl\n\t\t\t\t\tdisplayName\n\t\t\t\t}\n\t\t\t\tmessage\n\t\t\t}\n        }\n\t\tactivityFeedArticle(id: $articleId) {\n            ... on ActivityFeedEntity {\n                ...FeedItemFragment\n            }\n            ... on ActivityFeedTopLevelPost {\n                ...FeedPostFragment\n            }\n            ... on ActivityFeedArticle {\n                ...ArticleDetailsFragment\n            }\n            ... on ActivityFeedAssignment {\n                ...AssignmentDetailsFragment\n            }\n        }\n    }\n"): (typeof documents)["\n\tquery CourseFeedPost($articleId: String!, $commentsId: String!) {\n\t\tactivityFeedCommentPage(id: $commentsId) {\n\t\t\tactivityFeedComments {\n\t\t\t\tid\n\t\t\t\ttype\n\t\t\t\tauthor {\n\t\t\t\t\timageUrl\n\t\t\t\t\tdisplayName\n\t\t\t\t}\n\t\t\t\tmessage\n\t\t\t}\n        }\n\t\tactivityFeedArticle(id: $articleId) {\n            ... on ActivityFeedEntity {\n                ...FeedItemFragment\n            }\n            ... on ActivityFeedTopLevelPost {\n                ...FeedPostFragment\n            }\n            ... on ActivityFeedArticle {\n                ...ArticleDetailsFragment\n            }\n            ... on ActivityFeedAssignment {\n                ...AssignmentDetailsFragment\n            }\n        }\n    }\n"];
export function graphql(source: "\n    query CoursePage($id: String!, $orgUnitId: String!) {\n        organization(id: $id) {\n            name\n            imageUrl\n            homeUrl\n        }\n        activityFeedArticlePage(orgUnitId: $orgUnitId) {\n            id\n            activityFeedArticles {\n                __typename\n                ... on ActivityFeedEntity {\n                    ...FeedItemFragment\n                }\n                ... on ActivityFeedTopLevelPost {\n                    ...FeedPostFragment\n                }\n                ... on ActivityFeedArticle {\n                    ...ArticleDetailsFragment\n                }\n                ... on ActivityFeedAssignment {\n                    ...AssignmentDetailsFragment\n                }\n            }\n        }\n    }\n    fragment FeedItemFragment on ActivityFeedEntity {\n        id\n        type\n        author {\n            displayName\n            imageUrl\n        }\n        publishedDate\n    }\n    fragment FeedPostFragment on ActivityFeedTopLevelPost {\n        commentsLink\n        commentsCount\n        attachmentLinks {\n            id\n            type\n            name\n            href\n            iconHref\n        }\n        isPinned\n    }\n    fragment ArticleDetailsFragment on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetailsFragment on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n"): (typeof documents)["\n    query CoursePage($id: String!, $orgUnitId: String!) {\n        organization(id: $id) {\n            name\n            imageUrl\n            homeUrl\n        }\n        activityFeedArticlePage(orgUnitId: $orgUnitId) {\n            id\n            activityFeedArticles {\n                __typename\n                ... on ActivityFeedEntity {\n                    ...FeedItemFragment\n                }\n                ... on ActivityFeedTopLevelPost {\n                    ...FeedPostFragment\n                }\n                ... on ActivityFeedArticle {\n                    ...ArticleDetailsFragment\n                }\n                ... on ActivityFeedAssignment {\n                    ...AssignmentDetailsFragment\n                }\n            }\n        }\n    }\n    fragment FeedItemFragment on ActivityFeedEntity {\n        id\n        type\n        author {\n            displayName\n            imageUrl\n        }\n        publishedDate\n    }\n    fragment FeedPostFragment on ActivityFeedTopLevelPost {\n        commentsLink\n        commentsCount\n        attachmentLinks {\n            id\n            type\n            name\n            href\n            iconHref\n        }\n        isPinned\n    }\n    fragment ArticleDetailsFragment on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetailsFragment on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n"];
export function graphql(source: "\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;