/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "\n\tquery CoursePage($id: String!, $orgUnitId: String!) {\n\t\torganization(id: $id) {\n\t\t\tname\n\t\t\timageUrl\n\t\t\thomeUrl\n        }\n\t\tactivityFeedArticlePage(orgUnitId: $orgUnitId) {\n\t\t\tactivityFeedArticles {\n\t\t\t\t__typename\n\t\t\t\t... on ActivityFeedEntity {\n\t\t\t\t\t...FeedItem\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedTopLevelPost {\n\t\t\t\t\t...FeedPost\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedArticle {\n\t\t\t\t\t...ArticleDetails\n                }\n\t\t\t\t... on ActivityFeedAssignment {\n\t\t\t\t\t...AssignmentDetails\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\tfragment FeedItem on ActivityFeedEntity {\n\t\tid\n\t\ttype\n\t\tauthor {\n\t\t\tdisplayName\n\t\t\timageUrl\n\t\t}\n\t\tpublishedDate\n\t}\n\tfragment FeedPost on ActivityFeedTopLevelPost {\n\t\tcommentsLink\n\t\tcommentsCount\n\t\tattachmentLinks {\n\t\t\tid\n\t\t\ttype\n\t\t\tname\n\t\t\thref\n\t\t\ticonHref\n\t\t}\n\t\tisPinned\n\t}\n    fragment ArticleDetails on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetails on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n": types.CoursePageDocument,
    "\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.CourseListDocument,
};

export function graphql(source: "\n\tquery CoursePage($id: String!, $orgUnitId: String!) {\n\t\torganization(id: $id) {\n\t\t\tname\n\t\t\timageUrl\n\t\t\thomeUrl\n        }\n\t\tactivityFeedArticlePage(orgUnitId: $orgUnitId) {\n\t\t\tactivityFeedArticles {\n\t\t\t\t__typename\n\t\t\t\t... on ActivityFeedEntity {\n\t\t\t\t\t...FeedItem\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedTopLevelPost {\n\t\t\t\t\t...FeedPost\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedArticle {\n\t\t\t\t\t...ArticleDetails\n                }\n\t\t\t\t... on ActivityFeedAssignment {\n\t\t\t\t\t...AssignmentDetails\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\tfragment FeedItem on ActivityFeedEntity {\n\t\tid\n\t\ttype\n\t\tauthor {\n\t\t\tdisplayName\n\t\t\timageUrl\n\t\t}\n\t\tpublishedDate\n\t}\n\tfragment FeedPost on ActivityFeedTopLevelPost {\n\t\tcommentsLink\n\t\tcommentsCount\n\t\tattachmentLinks {\n\t\t\tid\n\t\t\ttype\n\t\t\tname\n\t\t\thref\n\t\t\ticonHref\n\t\t}\n\t\tisPinned\n\t}\n    fragment ArticleDetails on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetails on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n"): (typeof documents)["\n\tquery CoursePage($id: String!, $orgUnitId: String!) {\n\t\torganization(id: $id) {\n\t\t\tname\n\t\t\timageUrl\n\t\t\thomeUrl\n        }\n\t\tactivityFeedArticlePage(orgUnitId: $orgUnitId) {\n\t\t\tactivityFeedArticles {\n\t\t\t\t__typename\n\t\t\t\t... on ActivityFeedEntity {\n\t\t\t\t\t...FeedItem\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedTopLevelPost {\n\t\t\t\t\t...FeedPost\n\t\t\t\t}\n\t\t\t\t... on ActivityFeedArticle {\n\t\t\t\t\t...ArticleDetails\n                }\n\t\t\t\t... on ActivityFeedAssignment {\n\t\t\t\t\t...AssignmentDetails\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\tfragment FeedItem on ActivityFeedEntity {\n\t\tid\n\t\ttype\n\t\tauthor {\n\t\t\tdisplayName\n\t\t\timageUrl\n\t\t}\n\t\tpublishedDate\n\t}\n\tfragment FeedPost on ActivityFeedTopLevelPost {\n\t\tcommentsLink\n\t\tcommentsCount\n\t\tattachmentLinks {\n\t\t\tid\n\t\t\ttype\n\t\t\tname\n\t\t\thref\n\t\t\ticonHref\n\t\t}\n\t\tisPinned\n\t}\n    fragment ArticleDetails on ActivityFeedArticle {\n        message\n    }\n    fragment AssignmentDetails on ActivityFeedAssignment {\n        name\n        instructions\n        dueDate\n        submissionLink\n    }\n"];
export function graphql(source: "\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n    query CourseList($startDate: String!, $endDate: String!) {\n        activities(start: $startDate, end: $endDate) {\n            id\n            source {\n                id\n                name\n            }\n            organization {\n                id\n            }\n            completed\n\t\t\tcompletionDate\n\t\t\tdueDate\n        }\n\t\tenrollmentPage {\n\t\t\tenrollments {\n\t\t\t\torganization {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\timageUrl\n\t\t\t\t\tstartDate\n\t\t\t\t\tendDate\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;